### ISSUE TITLE
Fresh build fails to launch on EndeavourOS

### ISSUE THREAD

**Issue by nemaulatka** [nine7nine/Wine-NSPA#7] opened 2023-08-19 13:53 UTC
Hello!

Been using Wine-NSPA for quite a while, but as of now on EndeavourOS (arch-based distro) it fails to run with following error:

Fatal glibc error: allocatestack.c:333 (allocate_stack): assertion failed: size != 0

Recompiling didn't help. Would appreciate any advice and thank you for your work!

**Comment by nine7nine** [comment] 2023-08-20 04:10
I think i hit that error once, on a fresh install when i had set some of the rlimits related stuff...

is it possible an update has changed some of your system related settings (eg: in /etc/systemd/*.conf)

I'll do a bit of research anyway though -- as while i suspect that it is something system related, not to do with wine itself - I could be always wrong.

**Comment by nine7nine** [comment] 2023-08-27 16:28
@nemaulatka 

did you ever figure the cause on your system here?

you might want to check a few lines in your systemd config files (etc/systemd/ -- user.conf && system.conf)

the relevant ones are:

DefaultLimitNOFILE=1024:16777216
DefaultLimitNPROC=500000
DefaultLimitMEMLOCK=infinity
DefaultLimitRTPRIO=98

if you have some low / default limit set on these - that might explain why it's failing to allocate (first 3 are really what you ant to set)

**Comment by nine7nine** [comment] 2023-11-05 14:32
I'm closing this, since i have not got any kind of response.

**Closed by nine7nine** 2023-11-05 14:32 UTC
